### ISSUE TITLE
(Seemingly) infinite loop on some files

### ISSUE THREAD

**Issue by Unit2Ed** [jzebedee/deltaq#5]
We're finding that occasionally the delta generator gets stuck on particular files - most complex deltas finish within a few minutes, but in this case I've left it running overnight without result.

It spends hours at a time inside the "for (var scsc = scan += len; scan < newData.Length; scan++)" loop. It seems like the algorithm does progress (as occasionally that loop finishes, and then goes round the while loop again).

The problematic files are both 32MB in size and feature sporadic differences where individual bytes have been changed. I can provide a sample if it'd be useful, but I'm mostly wondering if this is something you've seen before?

**Comment by kamronbatman** [comment]
Having the same issues with a file that is 136MB and ~200MB.

**Comment by jzebedee** [comment]
@Unit2Ed @kamronbatman Can you share a sample file to repro?

**Comment by jzebedee** [comment]
I'd be happy to reopen this if you can find some inputs that trigger the issue. DQ2 fixed several corner cases that were identified from fuzzing in the original bsdiff implementation, so it's possible that it was resolved through that.
